insert into admin values (1,'Mario','Rossi');
insert into admin values (2,'Luigi','Verdi');

insert into docente values (1,'Mario','Bianchi');
insert into docente values (2,'Gianni','Neri');
insert into docente values (3,'Paolo','Belloni');

insert into corso values (1,'Analisi','04-GEN-2022','05-LUG-2022',2000.00,'Corso di Analisi matematica','AulaA1',1);
insert into corso values (2,'Programmazione Java Base','01-GEN-2022','01-MAR-2022',800.00,'Corso di programmazione base in Java','AulaA2',1);
insert into corso values (3,'Inglese','21-GIU-2022','11-SET-2022',900.00,'Livello B2','AulaB1',2);
insert into corso values (4,'Chimica','25-AGO-2022','2-DIC-2022',1700.00,'Corso di Chimica base','AulaC3',3);
insert into corso values (5,'Programmazione Java Advanced','12-GIU-2022','30-OTT-2022',2600.00,'Corso di programmazione avanzato di Java','AulaC1',2);

insert into corsista values (1,'Gino','Verdi',1);
insert into corsista values (2,'Lucia','Massi',0);
insert into corsista values (3,'Antonello','Ardizzone',0);
insert into corsista values (4,'Gerardo','Pavanetto',1);
insert into corsista values (5,'Laura','Scaffidi',1);
insert into corsista values (6,'Vittoria','Tinari',0);
insert into corsista values (7,'Giovanni','Blu',0);
insert into corsista values (8,'Fiorenzo','Pioggi',1);
insert into corsista values (9,'Anna','Gucci',0);
insert into corsista values (10,'Aldina','Borriello',0);
insert into corsista values (11,'Eleonora','Cattaneo',0);
insert into corsista values (12,'Alessio','Schiavone',1);
insert into corsista values (13,'Angela','Cocci',1);
insert into corsista values (14,'Giuseppe','Buonanno',1);
insert into corsista values (15,'Augusto','Todaro',0);

insert into corsistacorso values(1,1);
insert into corsistacorso values(1,2);
insert into corsistacorso values(2,2);
insert into corsistacorso values(2,4);
insert into corsistacorso values(3,1);
insert into corsistacorso values(3,5);
insert into corsistacorso values(4,1);
insert into corsistacorso values(5,2);
insert into corsistacorso values(5,3);
insert into corsistacorso values(5,4);
insert into corsistacorso values(5,5);
insert into corsistacorso values(6,2);
insert into corsistacorso values(6,3);
insert into corsistacorso values(7,1);
insert into corsistacorso values(7,2);
insert into corsistacorso values(7,3);
insert into corsistacorso values(8,1);
insert into corsistacorso values(8,4);
insert into corsistacorso values(9,1);
insert into corsistacorso values(9,2);
insert into corsistacorso values(9,4);
insert into corsistacorso values(10,1);
insert into corsistacorso values(10,3);
insert into corsistacorso values(10,5);
insert into corsistacorso values(11,3);
insert into corsistacorso values(11,4);
insert into corsistacorso values(12,1);
insert into corsistacorso values(12,3);
insert into corsistacorso values(12,4);
insert into corsistacorso values(13,1);
insert into corsistacorso values(13,3);
insert into corsistacorso values(13,5);
insert into corsistacorso values(14,1);
insert into corsistacorso values(14,2);
insert into corsistacorso values(14,3);
insert into corsistacorso values(14,5);
insert into corsistacorso values(15,1);
insert into corsistacorso values(15,4);
